// <auto-generated />
using System;
using Assignment4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Assignment4.Migrations
{
    [DbContext(typeof(optionContext))]
    [Migration("20251211053150_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Asian_option", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<double>("K")
                        .HasColumnType("double precision")
                        .HasColumnName("strike");

                    b.Property<double>("b")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("expdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expirydate");

                    b.Property<string>("otyp")
                        .HasColumnType("text");

                    b.Property<int?>("ratecurveid")
                        .HasColumnType("integer");

                    b.Property<double>("sig")
                        .HasColumnType("double precision")
                        .HasColumnName("vol");

                    b.Property<int>("underlyingid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("ratecurveid");

                    b.HasIndex("underlyingid");

                    b.ToTable("asian_option", (string)null);
                });

            modelBuilder.Entity("Barrier_option", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<double>("Barrier")
                        .HasColumnType("double precision")
                        .HasColumnName("barrierlevel");

                    b.Property<string>("BarrierType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("barriertype");

                    b.Property<double>("K")
                        .HasColumnType("double precision")
                        .HasColumnName("strike");

                    b.Property<double>("b")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("expdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expirydate");

                    b.Property<string>("otyp")
                        .HasColumnType("text");

                    b.Property<int?>("ratecurveid")
                        .HasColumnType("integer");

                    b.Property<double>("sig")
                        .HasColumnType("double precision")
                        .HasColumnName("vol");

                    b.Property<int>("underlyingid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("ratecurveid");

                    b.HasIndex("underlyingid");

                    b.ToTable("barrier_option", (string)null);
                });

            modelBuilder.Entity("Digital_option", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<double>("K")
                        .HasColumnType("double precision")
                        .HasColumnName("strike");

                    b.Property<double>("b")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("expdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expirydate");

                    b.Property<string>("otyp")
                        .HasColumnType("text");

                    b.Property<double>("payout_amount")
                        .HasColumnType("double precision")
                        .HasColumnName("payout_amount");

                    b.Property<int?>("ratecurveid")
                        .HasColumnType("integer");

                    b.Property<double>("sig")
                        .HasColumnType("double precision")
                        .HasColumnName("vol");

                    b.Property<int>("underlyingid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("ratecurveid");

                    b.HasIndex("underlyingid");

                    b.ToTable("digital_option", (string)null);
                });

            modelBuilder.Entity("Exchange", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("exchangeid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime>("updateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("id");

                    b.ToTable("exchange");
                });

            modelBuilder.Entity("Lookback_option", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<double>("K")
                        .HasColumnType("double precision")
                        .HasColumnName("strike");

                    b.Property<double>("b")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("expdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expirydate");

                    b.Property<string>("otyp")
                        .HasColumnType("text");

                    b.Property<int?>("ratecurveid")
                        .HasColumnType("integer");

                    b.Property<double>("sig")
                        .HasColumnType("double precision")
                        .HasColumnName("vol");

                    b.Property<int>("underlyingid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("ratecurveid");

                    b.HasIndex("underlyingid");

                    b.ToTable("lookback_option", (string)null);
                });

            modelBuilder.Entity("Market", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("marketid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("Exchangeid")
                        .HasColumnType("integer")
                        .HasColumnName("exchangeid");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("id");

                    b.HasIndex("Exchangeid");

                    b.ToTable("market");
                });

            modelBuilder.Entity("Option", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<double>("K")
                        .HasColumnType("double precision")
                        .HasColumnName("strike");

                    b.Property<double>("b")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("expdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expirydate");

                    b.Property<string>("otyp")
                        .HasColumnType("text");

                    b.Property<int?>("ratecurveid")
                        .HasColumnType("integer");

                    b.Property<double>("sig")
                        .HasColumnType("double precision")
                        .HasColumnName("vol");

                    b.Property<int>("underlyingid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("ratecurveid");

                    b.HasIndex("underlyingid");

                    b.ToTable("option", (string)null);
                });

            modelBuilder.Entity("Range_option", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<double>("b")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("expdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expirydate");

                    b.Property<int?>("ratecurveid")
                        .HasColumnType("integer");

                    b.Property<double>("sig")
                        .HasColumnType("double precision")
                        .HasColumnName("vol");

                    b.Property<int>("underlyingid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("ratecurveid");

                    b.HasIndex("underlyingid");

                    b.ToTable("range_option", (string)null);
                });

            modelBuilder.Entity("historicalPrice", b =>
                {
                    b.Property<int>("historicalpriceid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("historicalpriceid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("historicalpriceid"));

                    b.Property<double>("LastPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("lastprice");

                    b.Property<DateTime>("PriceTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pricetime");

                    b.Property<int>("underlyingid")
                        .HasColumnType("integer");

                    b.HasKey("historicalpriceid");

                    b.HasIndex("underlyingid");

                    b.ToTable("historicalprice", (string)null);
                });

            modelBuilder.Entity("rateCurve", b =>
                {
                    b.Property<int>("RateCurveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ratecurveid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RateCurveId"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<DateTime>("CurveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("curvedate");

                    b.Property<string>("CurveName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("curvename");

                    b.HasKey("RateCurveId");

                    b.ToTable("ratecurve");
                });

            modelBuilder.Entity("ratePoint", b =>
                {
                    b.Property<int>("RatePointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ratepointid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RatePointId"));

                    b.Property<double>("Rate")
                        .HasColumnType("double precision")
                        .HasColumnName("rate");

                    b.Property<double>("Tenor")
                        .HasColumnType("double precision")
                        .HasColumnName("tenor");

                    b.Property<int>("ratecurveid")
                        .HasColumnType("integer");

                    b.HasKey("RatePointId");

                    b.HasIndex("ratecurveid");

                    b.ToTable("ratepoint");
                });

            modelBuilder.Entity("underlying", b =>
                {
                    b.Property<int>("underlyingid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("underlyingid");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("underlyingid"));

                    b.Property<string>("assettype")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assettype");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("symbol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symbol");

                    b.HasKey("underlyingid");

                    b.ToTable("underlying");
                });

            modelBuilder.Entity("Asian_option", b =>
                {
                    b.HasOne("rateCurve", "ratecurve")
                        .WithMany()
                        .HasForeignKey("ratecurveid");

                    b.HasOne("underlying", "Underlying")
                        .WithMany("asian_option")
                        .HasForeignKey("underlyingid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Underlying");

                    b.Navigation("ratecurve");
                });

            modelBuilder.Entity("Barrier_option", b =>
                {
                    b.HasOne("rateCurve", "Ratecurve")
                        .WithMany()
                        .HasForeignKey("ratecurveid");

                    b.HasOne("underlying", "underlying")
                        .WithMany("barrier_option")
                        .HasForeignKey("underlyingid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ratecurve");

                    b.Navigation("underlying");
                });

            modelBuilder.Entity("Digital_option", b =>
                {
                    b.HasOne("rateCurve", "Ratecurve")
                        .WithMany()
                        .HasForeignKey("ratecurveid");

                    b.HasOne("underlying", "underlying")
                        .WithMany("digital_option")
                        .HasForeignKey("underlyingid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ratecurve");

                    b.Navigation("underlying");
                });

            modelBuilder.Entity("Lookback_option", b =>
                {
                    b.HasOne("rateCurve", "Ratecurve")
                        .WithMany()
                        .HasForeignKey("ratecurveid");

                    b.HasOne("underlying", "underlying")
                        .WithMany("lookback_option")
                        .HasForeignKey("underlyingid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ratecurve");

                    b.Navigation("underlying");
                });

            modelBuilder.Entity("Market", b =>
                {
                    b.HasOne("Exchange", "exchange")
                        .WithMany("Markets")
                        .HasForeignKey("Exchangeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("exchange");
                });

            modelBuilder.Entity("Option", b =>
                {
                    b.HasOne("rateCurve", "Ratecurve")
                        .WithMany()
                        .HasForeignKey("ratecurveid");

                    b.HasOne("underlying", "underlying")
                        .WithMany("options")
                        .HasForeignKey("underlyingid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ratecurve");

                    b.Navigation("underlying");
                });

            modelBuilder.Entity("Range_option", b =>
                {
                    b.HasOne("rateCurve", "Ratecurve")
                        .WithMany()
                        .HasForeignKey("ratecurveid");

                    b.HasOne("underlying", "underlying")
                        .WithMany("range_option")
                        .HasForeignKey("underlyingid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ratecurve");

                    b.Navigation("underlying");
                });

            modelBuilder.Entity("historicalPrice", b =>
                {
                    b.HasOne("underlying", "Underlying")
                        .WithMany("prices")
                        .HasForeignKey("underlyingid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Underlying");
                });

            modelBuilder.Entity("ratePoint", b =>
                {
                    b.HasOne("rateCurve", "RateCurve")
                        .WithMany("RatePoints")
                        .HasForeignKey("ratecurveid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RateCurve");
                });

            modelBuilder.Entity("Exchange", b =>
                {
                    b.Navigation("Markets");
                });

            modelBuilder.Entity("rateCurve", b =>
                {
                    b.Navigation("RatePoints");
                });

            modelBuilder.Entity("underlying", b =>
                {
                    b.Navigation("asian_option");

                    b.Navigation("barrier_option");

                    b.Navigation("digital_option");

                    b.Navigation("lookback_option");

                    b.Navigation("options");

                    b.Navigation("prices");

                    b.Navigation("range_option");
                });
#pragma warning restore 612, 618
        }
    }
}
